pipeline:
  name: aziz-pipeline-3
  identifier: azizpipeline3
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: A
        identifier: A
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: A1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "stage A"
                          env="<+project.name>"
                    environmentVariables: []
                    outputVariables:
                      - name: env_output
                        type: String
                        value: env
                  timeout: 10m
        tags: {}
    - stage:
        name: APPROVAL STEP
        identifier: APPROVAL_STEP
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: my-approval
                  identifier: myapproval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - _project_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - parallel:
        - stage:
            name: B
            identifier: B
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: B1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: echo "stage B"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
            tags: {}
        - stage:
            name: C
            identifier: C
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: C1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: echo "stage C"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
            tags: {}
    - stage:
        name: D
        identifier: D
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: D1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "stage D"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  notificationRules:
    - name: NOTIF-AZIZ
      identifier: NOTIFAZIZ
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - azaifel@gmail.com
      enabled: false
